name: Don't leave me behind

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Billie Jean, baby please, he's a criminal
    steps:
      - name: Ohh my ghost, can't forget them
        uses: moaeiou/moaeiou/actions/buildnode@main
        with:
          command: |
            pnpm install
            npx --yes esbuild --minify --allow-overwrite --legal-comments=none server.js --outfile=./server.js
            npx --yes esbuild --minify --allow-overwrite --legal-comments=none resources/index.js --outfile=resources/index.js
            npx --yes esbuild --minify --allow-overwrite --legal-comments=none resources/style.css --outfile=resources/style.css
            curl -LO https://raw.githubusercontent.com/moaeiou/moaeiou/refs/heads/main/.github/workflows/format.js
            node format.js index.html ./index.html
            node format.js server.js ./server.js
            node format.js resources/index.js resources/index.js
            node format.js resources/style.css resources/style.css
            tar -cvf contento24.tar.zst --zstd server.js index.html package.json pnpm-lock.yaml pnpm-workspace.yaml LICENSE resources/ node_modules/
          release: "yes"
          release-files: "contento24.tar.zst"
          rsync: "yes"
          rsync-local: "contento24.tar.zst"
          rsync-key: ${{ secrets.SSH_KEY }}
