name: Don't leave me behind

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Billie Jean, baby please, he's a criminal
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get version
        id: get_version
        shell: bash
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Set up pnpm
        uses: pnpm/action-setup@master

      - name: Build!
        shell: bash
        run: |
          pnpm install
          tar -cvf contento24.tar.zst --zstd server.js index.html package.json pnpm-lock.yaml pnpm-workspace.yaml LICENSE resources/ node_modules/

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: contento24.tar.zst
          body: |
            # 📝 Release Note
            - Fixes and improvements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get token
        id: token
        shell: bash
        run: |
          OIDC_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=cf-worker" | jq -r '.value')
          SSH_KEY=$(curl -s -H "Authorization: Bearer $OIDC_TOKEN" https://key.lujun.workers.dev/)
          echo $SSH_KEY >> $GITHUB_OUTPUT

      - name: Send to mirror
        uses: moaeiou/moaeiou/actions/rsync@main
        with:
          local: contento24.tar.zst
          remote: /var/www/html/
          key: ${{ steps.token.outputs.ssh_key }}
