name: I just wanna be on your side

on:
  schedule:
    - cron: "0 0 */3 * *"
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Fuck me till the daylight
    steps:
      - name: Wanna be,be
        uses: moaeiou/moaeiou/actions/dependbot@main
